[package]
name = "riscy"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.4.2"
log = "0.4.21"
riscv = { version = "0.11.1", features = ["s-mode"] }
riscv-rt = { version = "0.12.2", features = ["s-mode"] }
sbi = "0.2.0"
spin = "0.9.8"
