[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x", 
  "-C", "link-arg=-Tlink.x"
]
runner = "qemu-system-riscv64 -machine virt -cpu rv64 -m 128M -kernel "

[unstable]
build-std = ["core", "alloc"]
