[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
rustflags = [  
  "-C", "link-arg=-Tkernel.ld",
]
runner = "qemu-system-riscv64"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
